site_name:        CUSPARSE.jl
repo_url:         https://github.com/JuliaGPU/CUSPARSE.jl
site_description: Documentation for Julia wrappers of NVIDIA's CUSPARSE library.
site_author:      kshyatt

theme: readthedocs

extra_css:
      - assets/Documenter.css

extra_javascript:
      - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
          - assets/mathjaxhelper.js

markdown_extensions:
      - extra
          - tables
              - fenced_code
                  - mdx_math

docs_dir: 'build'

pages:
      - Home: index.md
